### ISSUE TITLE
page starting lower and auto-scrolls

### ISSUE THREAD

**Issue by tomstuart123** [decentdao/decent-interface#1812] opened 2024-05-17 17:13 UTC
**dara.khan left a comment:**

![recording](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjY0NzgwODkyYzg2YzIwMDA4OGI1Nzg5IiwiaWQiOiIzMGIyNzY4Yi03OWM1LTQxMjYtOTc4NC00YWEzZWY5ODFlZDcifQ==)

Sometimes on desktop and mobile, when I click Next > to the Configure page, sometimes the page starts lower and auto-scrolls up, capturing vid in Netlify

<details><summary>Browser metadata</summary>

```
Path:      /create
Browser:   Chrome 124.0.0.0 on Mac OS 10.15.7
Viewport:  1011 x 817 @1x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1578.app.dev.fractalframework.xyz%2Fcreate&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=124.0&resolution=1011x817&speed=1&start=true&ref=netlify-source)

</details>

[Open Deploy Preview](https://deploy-preview-1578.app.dev.fractalframework.xyz/create) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=664780892c86c200088b5789&commentID=66478456a98b79f626f5790e&resolution=resolved)

_Originally posted by @netlify[bot] in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2117949073_

**Comment by adamgall** [comment] 2024-05-22 21:07
Closing, this is the intended behavior

**Closed by adamgall** 2024-05-22 21:07 UTC
Labels: enhancement
